import{createHmac}from'node:crypto';import{mkdtempSync,rmSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{afterEach,describe,expect,it}from'vitest';import{openDatabase}from'./database.js';import{AccountOwnershipStore}from'./account-ownership.js';import{importSignedAccountSnapshot,latestImportedAccountSnapshot}from'./imported-account-snapshot.js';import{ProtectionReconciliationStore}from'./protection-reconciliation.js';
const dirs:string[]=[],secret='s'.repeat(32);function canonical(v:any):string{if(v===null)return'null';if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(',')}}`;return JSON.stringify(v)}function h(){const d=mkdtempSync(join(tmpdir(),'gct-import-'));dirs.push(d);const db=openDatabase(join(d,'db.sqlite'),resolve(process.cwd(),'../../migrations')),file=join(d,'snapshot.json'),book=join(d,'book.json');new AccountOwnershipStore(db).seedAccount('acct','Account','gate-crossex-default','admin');writeFileSync(book,JSON.stringify({updated_at_ms:Date.parse('2026-08-24T00:00:00Z'),entries:[]}));return{db,file,book}}function write(file:string,positions:any[]=[],at=Date.parse('2026-08-24T00:00:00Z'),signatureSecret=secret){const payload={contract:'gate-crossex-account-snapshot/v1',accountId:'acct',generatedAtMs:at,scope:'all-crossex-futures-positions',queryComplete:true,positionCount:positions.length,positions},signature=createHmac('sha256',signatureSecret).update(canonical(payload)).digest('hex');writeFileSync(file,JSON.stringify({...payload,signatureAlgorithm:'HMAC-SHA256',signature}));}afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true})});
describe('signed account snapshot import',()=>{
 it('imports and reuses a valid snapshot',()=>{const{db,file}=h();write(file);const a=importSignedAccountSnapshot(db,'acct',file,secret,new Date('2026-08-24T00:01:00Z')),b=importSignedAccountSnapshot(db,'acct',file,secret,new Date('2026-08-24T00:02:00Z'));expect(a.reused).toBe(false);expect(b.reused).toBe(true);expect(latestImportedAccountSnapshot(db,'acct')?.positions).toEqual([]);db.close()});
 it('accepts the Python canonical signing vector',()=>{const{db,file}=h();const payload={contract:'gate-crossex-account-snapshot/v1',accountId:'acct',generatedAtMs:1787529600000,scope:'all-crossex-futures-positions',queryComplete:true,positionCount:1,positions:[{symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quantity:'1.25'}]};writeFileSync(file,JSON.stringify({...payload,signatureAlgorithm:'HMAC-SHA256',signature:'a7a34c7be4eb634928cc77ef12312206c2c2cc292ba2e25ebe1940b3ea9685ef'}));expect(importSignedAccountSnapshot(db,'acct',file,secret,new Date(1787529601000)).reused).toBe(false);db.close()});
 it('rejects invalid signature account and stale evidence',()=>{const{db,file}=h();write(file);expect(()=>importSignedAccountSnapshot(db,'acct',file,'x'.repeat(32),new Date('2026-08-24T00:01:00Z'))).toThrow('account_snapshot_signature_invalid');expect(()=>importSignedAccountSnapshot(db,'other',file,secret,new Date('2026-08-24T00:01:00Z'))).toThrow('account_snapshot_account_mismatch');expect(()=>importSignedAccountSnapshot(db,'acct',file,secret,new Date('2026-08-24T00:06:00Z'))).toThrow('account_snapshot_stale');db.close()});
 it('rejects snapshot time regression',()=>{const{db,file}=h();write(file,[],Date.parse('2026-08-24T00:01:00Z'));importSignedAccountSnapshot(db,'acct',file,secret,new Date('2026-08-24T00:02:00Z'));write(file,[],Date.parse('2026-08-24T00:00:00Z'));expect(()=>importSignedAccountSnapshot(db,'acct',file,secret,new Date('2026-08-24T00:02:00Z'))).toThrow('account_snapshot_time_regression');db.close()});
 it('lets protection reconciliation trust a fresh signed empty snapshot without Canary credentials',()=>{const{db,file,book}=h();write(file);const store=new ProtectionReconciliationStore(db,'acct',book,file,secret),result=store.create('acct',new Date('2026-08-24T00:01:00Z'));expect(result.report).toMatchObject({status:'MATCH',confidence:'HIGH',credentialVerifiedAt:null,snapshotFetchedAt:'2026-08-24T00:00:00.000Z'});expect(db.prepare('SELECT COUNT(*) count FROM execution_orders').get()).toEqual({count:0});db.close()});
});
