import {createHash,randomUUID} from 'node:crypto';
import {lstatSync,readFileSync,realpathSync,statSync} from 'node:fs';
import {basename} from 'node:path';
import type Database from 'better-sqlite3';
import {Decimal} from 'decimal.js';
import {z} from 'zod';
import{importSignedAccountSnapshot,latestImportedAccountSnapshot}from'./imported-account-snapshot.js';

const FRESH_MS=10*60_000;
const BookSchema=z.object({updated_at_ms:z.number().int().nonnegative(),entries:z.array(z.object({symbol:z.string(),side:z.enum(['BUY','SELL'])}).passthrough())}).passthrough();
export interface ProtectionReconciliation{reconciliationId:string;createdAt:string;accountId:string;status:'MATCH'|'DIFFERENT'|'UNCOMPARABLE';confidence:'HIGH'|'LOW';reasons:string[];bookName:string;bookUpdatedAtMs:number|null;credentialVerifiedAt:string|null;snapshotFetchedAt:string|null;bookEntries:Array<{symbol:string;side:'BUY'|'SELL'}>;livePositions:Array<{symbol:string;side:'BUY'|'SELL';updatedAt:string}>;missingProtection:string[];extraProtection:string[];quantityComparable:false}
function hash(value:unknown){return`sha256:${createHash('sha256').update(JSON.stringify(value)).digest('hex')}`}
function key(item:{symbol:string;side:string}){return`${item.symbol.toUpperCase()}|${item.side}`}
export function reconcileProtectionBook(database:Database.Database,accountId:string,bookPath:string,now=new Date(),externalReasons:string[]=[],allowNativeAccountState=true):ProtectionReconciliation{
 const reasons:string[]=[...externalReasons],nowMs=now.getTime();let bookUpdatedAtMs:number|null=null,bookName=basename(bookPath),bookEntries:ProtectionReconciliation['bookEntries']=[];
 try{if(lstatSync(bookPath).isSymbolicLink())throw new Error('symlink prohibited');const resolved=realpathSync(bookPath);bookName=basename(resolved);const stat=statSync(resolved),raw=JSON.parse(readFileSync(resolved,'utf8')),book=BookSchema.parse(raw);bookUpdatedAtMs=book.updated_at_ms;bookEntries=book.entries.map(e=>({symbol:e.symbol.toUpperCase(),side:e.side}));if(nowMs-stat.mtimeMs>FRESH_MS||nowMs-book.updated_at_ms>FRESH_MS||book.updated_at_ms>nowMs)reasons.push('protection_book_stale')}catch{reasons.push('protection_book_unavailable')}
 const accounts=database.prepare('SELECT id,credential_profile_id FROM cloud_accounts WHERE enabled=1').all() as Array<{id:string;credential_profile_id:string}>;
 const account=accounts.length===1&&accounts[0]?.id===accountId?accounts[0]:undefined;if(!account)reasons.push('single_account_snapshot_boundary_unavailable');
 const imported=account?latestImportedAccountSnapshot(database,accountId):null;let credentialVerifiedAt:string|null=null,snapshotFetchedAt:string|null=null,livePositions:ProtectionReconciliation['livePositions']=[];
 if(imported){snapshotFetchedAt=new Date(imported.generatedAtMs).toISOString();if(imported.generatedAtMs>nowMs||nowMs-imported.generatedAtMs>FRESH_MS)reasons.push('account_snapshot_stale');livePositions=imported.positions.filter(p=>!new Decimal(p.quantity).isZero()).map(p=>({symbol:p.symbol.toUpperCase(),side:p.side,updatedAt:snapshotFetchedAt!}))}
 else if(account&&allowNativeAccountState){const credential=database.prepare('SELECT last_verified_at FROM credential_metadata WHERE id=?').get(account.credential_profile_id) as {last_verified_at:string|null}|undefined;credentialVerifiedAt=credential?.last_verified_at??null;const verifiedMs=credentialVerifiedAt?Date.parse(credentialVerifiedAt):NaN;if(!credentialVerifiedAt)reasons.push('account_snapshot_credentials_unavailable');else if(!Number.isFinite(verifiedMs)||verifiedMs>nowMs||nowMs-verifiedMs>FRESH_MS)reasons.push('account_snapshot_stale');const snapshot=database.prepare('SELECT fetched_at FROM portfolio_snapshots ORDER BY fetched_at DESC LIMIT 1').get() as {fetched_at:string}|undefined;snapshotFetchedAt=snapshot?.fetched_at??null;const snapshotMs=snapshotFetchedAt?Date.parse(snapshotFetchedAt):NaN;if(!snapshotFetchedAt)reasons.push('account_snapshot_unavailable');else if(!Number.isFinite(snapshotMs)||snapshotMs>nowMs||nowMs-snapshotMs>FRESH_MS)reasons.push('account_snapshot_stale');const rows=database.prepare('SELECT symbol,quantity,updated_at FROM live_positions ORDER BY symbol,position_id').all() as Array<{symbol:string;quantity:string;updated_at:string}>;livePositions=rows.filter(r=>!new Decimal(r.quantity).isZero()).map(r=>({symbol:r.symbol.toUpperCase(),side:new Decimal(r.quantity).isPositive()?'BUY' as const:'SELL' as const,updatedAt:r.updated_at}))}
 if(livePositions.some(p=>{const at=Date.parse(p.updatedAt);return!Number.isFinite(at)||at>nowMs||nowMs-at>FRESH_MS}))reasons.push('live_positions_stale');
 const bookKeys=new Set(bookEntries.map(key)),positionKeys=new Set(livePositions.map(key));
 const missingProtection=[...positionKeys].filter(k=>!bookKeys.has(k)).sort(),extraProtection=[...bookKeys].filter(k=>!positionKeys.has(k)).sort();
 let status:ProtectionReconciliation['status'],confidence:ProtectionReconciliation['confidence'];
 if(reasons.length){status='UNCOMPARABLE';confidence='LOW'}else if(missingProtection.length||extraProtection.length){status='DIFFERENT';confidence='HIGH'}else if(bookEntries.length===0&&livePositions.length===0){status='MATCH';confidence='HIGH'}else{status='UNCOMPARABLE';confidence='LOW';reasons.push('protection_quantity_evidence_unavailable')}
 return{reconciliationId:randomUUID(),createdAt:now.toISOString(),accountId,status,confidence,reasons,bookName,bookUpdatedAtMs,credentialVerifiedAt,snapshotFetchedAt,bookEntries,livePositions,missingProtection,extraProtection,quantityComparable:false};
}
export class ProtectionReconciliationStore{constructor(private readonly db:Database.Database,private readonly accountId:string,private readonly bookPath:string,private readonly snapshotPath?:string,private readonly snapshotSecret?:string){}
 create(accountId:string,now=new Date()){if(accountId!==this.accountId)throw new Error('protection_reconciliation_account_mismatch');let importReasons:string[]=[];if(this.snapshotPath&&!this.snapshotSecret)importReasons=['account_snapshot_secret_missing'];if(this.snapshotPath&&this.snapshotSecret)try{importSignedAccountSnapshot(this.db,this.accountId,this.snapshotPath,this.snapshotSecret,now)}catch(error){importReasons=[error instanceof Error?error.message:'account_snapshot_import_failed']}const report=reconcileProtectionBook(this.db,this.accountId,this.bookPath,now,importReasons,!this.snapshotPath||importReasons.length===0),fingerprint=hash({bookUpdatedAtMs:report.bookUpdatedAtMs,credentialVerifiedAt:report.credentialVerifiedAt,snapshotFetchedAt:report.snapshotFetchedAt,bookEntries:report.bookEntries,livePositions:report.livePositions,status:report.status,reasons:report.reasons});return this.db.transaction(()=>{const result=this.db.prepare('INSERT INTO protection_book_reconciliations(id,account_id,evidence_fingerprint,status,confidence,report_json,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(account_id,evidence_fingerprint) DO NOTHING').run(report.reconciliationId,this.accountId,fingerprint,report.status,report.confidence,JSON.stringify(report),report.createdAt);if(result.changes===1)return{report,reused:false};const row=this.db.prepare('SELECT report_json FROM protection_book_reconciliations WHERE account_id=? AND evidence_fingerprint=?').get(this.accountId,fingerprint) as {report_json:string};return{report:JSON.parse(row.report_json) as ProtectionReconciliation,reused:true}})()}
 list(accountId:string){if(accountId!==this.accountId)return[];return(this.db.prepare('SELECT report_json FROM protection_book_reconciliations WHERE account_id=? ORDER BY created_at DESC LIMIT 50').all(accountId)as Array<{report_json:string}>).map(r=>JSON.parse(r.report_json) as ProtectionReconciliation)}
}
