import{mkdtempSync,rmSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{afterEach,describe,expect,it}from'vitest';import{openDatabase}from'./database.js';import{AccountOwnershipStore}from'./account-ownership.js';import{ProtectionReconciliationStore,reconcileProtectionBook}from'./protection-reconciliation.js';
const dirs:string[]=[];function h(entries:unknown[]=[],updatedAtMs=Date.parse('2026-08-24T00:00:00Z')){const dir=mkdtempSync(join(tmpdir(),'gct-protection-'));dirs.push(dir);const db=openDatabase(join(dir,'db.sqlite'),resolve(process.cwd(),'../../migrations')),book=join(dir,'book.json');writeFileSync(book,JSON.stringify({updated_at_ms:updatedAtMs,entries}));new AccountOwnershipStore(db).seedAccount('acct','Account','gate-crossex-default','admin',new Date('2026-08-24T00:00:00Z'));return{db,book}}afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true})});
function credential(db:any,at='2026-08-24T00:00:00.000Z'){db.prepare("INSERT INTO credential_metadata(id,label,provider,created_at,last_verified_at) VALUES('gate-crossex-default','Gate','env_file',?,?)").run(at,at)}
function snapshot(db:any,at='2026-08-24T00:00:00.000Z'){db.prepare("INSERT INTO portfolio_snapshots(id,fetched_at,remote_updated_at,payload_json) VALUES('snapshot',?,?, '{}')").run(at,at)}
function position(db:any,symbol='GATE_FUTURE_BTC_USDT',quantity='1',at='2026-08-24T00:00:00.000Z'){db.prepare("INSERT INTO live_positions(position_id,symbol,venue,quantity,entry_price,mark_price,realized_pnl,updated_at) VALUES('p',?,'GATE',?,'100','100','0',?)").run(symbol,quantity,at)}
describe('protection book reconciliation',()=>{
 it('never treats missing account evidence as a trusted empty match',()=>{const{db,book}=h();const r=reconcileProtectionBook(db,'acct',book,new Date('2026-08-24T00:01:00Z'));expect(r).toMatchObject({status:'UNCOMPARABLE',confidence:'LOW'});expect(r.reasons).toContain('account_snapshot_credentials_unavailable');db.close()});
 it('matches only fresh trusted empty evidence',()=>{const{db,book}=h();credential(db);snapshot(db);const r=reconcileProtectionBook(db,'acct',book,new Date('2026-08-24T00:01:00Z'));expect(r).toMatchObject({status:'MATCH',confidence:'HIGH',reasons:[]});db.close()});
 it('reports trusted coverage differences',()=>{const{db,book}=h();credential(db);snapshot(db);position(db);const r=reconcileProtectionBook(db,'acct',book,new Date('2026-08-24T00:01:00Z'));expect(r).toMatchObject({status:'DIFFERENT',confidence:'HIGH',missingProtection:['GATE_FUTURE_BTC_USDT|BUY']});db.close()});
 it('refuses a high-confidence non-empty match without protection quantity evidence',()=>{const{db,book}=h([{symbol:'GATE_FUTURE_BTC_USDT',side:'BUY'}]);credential(db);snapshot(db);position(db);const r=reconcileProtectionBook(db,'acct',book,new Date('2026-08-24T00:01:00Z'));expect(r).toMatchObject({status:'UNCOMPARABLE',confidence:'LOW',quantityComparable:false});expect(r.reasons).toContain('protection_quantity_evidence_unavailable');db.close()});
 it('does not reuse a fresh MATCH after unchanged evidence becomes stale',()=>{const{db,book}=h();credential(db);snapshot(db);const store=new ProtectionReconciliationStore(db,'acct',book),fresh=store.create('acct',new Date('2026-08-24T00:01:00Z')),stale=store.create('acct',new Date('2026-08-24T00:20:00Z'));expect(fresh.report.status).toBe('MATCH');expect(stale).toMatchObject({reused:false,report:{status:'UNCOMPARABLE'}});db.close()});
 it('persists idempotently without creating orders or crossing accounts',()=>{const{db,book}=h();credential(db);snapshot(db);const store=new ProtectionReconciliationStore(db,'acct',book),a=store.create('acct',new Date('2026-08-24T00:01:00Z')),b=store.create('acct',new Date('2026-08-24T00:02:00Z'));expect(a.reused).toBe(false);expect(b.reused).toBe(true);expect(store.list('other')).toEqual([]);expect(db.prepare('SELECT COUNT(*) count FROM execution_orders').get()).toEqual({count:0});expect(()=>store.create('other')).toThrow('protection_reconciliation_account_mismatch');db.close()});
});
