import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { openDatabase } from './database.js';
import { TargetShadowPlanStore } from './target-shadow-plan.js';
const dirs:string[]=[];
function harness(){const d=mkdtempSync(join(tmpdir(),'gct-shadow-'));dirs.push(d);const db=openDatabase(join(d,'db.sqlite'),resolve(process.cwd(),'../../migrations'));return{db,store:new TargetShadowPlanStore(db,'acct')}}
const target=(qty=100,side:'BUY'|'SELL'='BUY')=>({meta:{contract:'gate-crossex-target-state',contract_version:1,strategy_tag:'mainline'},positions:[{symbol:'BTCUSDT',target_side:side,target_quote_qty:qty,risk:{},route:{mode:'AUTO',allowed_exchanges:['GATE','BINANCE'],max_slippage_bps:40,min_depth_notional:500,max_venue_count:2,split_allowed:true,prefer_exchange:'GATE'}}]});
function pos(db:ReturnType<typeof harness>['db'],id:string,symbol:string,qty:string,price='100'){db.prepare(`INSERT INTO live_positions(position_id,symbol,venue,quantity,entry_price,mark_price,realized_pnl,updated_at) VALUES(?,?,?,?,'90',?,'0','2026-08-22T01:00:00.000Z')`).run(id,symbol,symbol.split('_')[0],qty,price)}
afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true})});
describe('TargetShadowPlanStore',()=>{
 it('compiles an empty account target into a preferred-venue shadow open',()=>{const{db,store}=harness();const {plan:p}=store.create(target(),'acct','planner',new Date('2026-08-22T02:00:00Z'));expect(p.executionAllowed).toBe(false);expect(p.actions).toEqual([expect.objectContaining({kind:'OPEN',symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quoteQuantity:'100',reduceOnly:false,reason:'increase_target_exposure',phase:1,dependsOnPhase:null,clipIndex:1,clipCount:1})]);expect(db.prepare('SELECT COUNT(*) count FROM execution_orders').get()).toEqual({count:0});db.close()});
 it('reduces same-side exposure proportionally',()=>{const{db,store}=harness();pos(db,'g','GATE_FUTURE_BTC_USDT','1');pos(db,'b','BINANCE_FUTURE_BTC_USDT','1');const {plan:p}=store.create(target(100),'acct','planner');expect(p.actions).toHaveLength(2);expect(p.actions.every(a=>a.kind==='REDUCE'&&a.reduceOnly)).toBe(true);expect(p.actions.map(a=>a.quoteQuantity)).toEqual(['50','50']);db.close()});
 it('opens only the same-side target remainder',()=>{const{db,store}=harness();pos(db,'g','GATE_FUTURE_BTC_USDT','0.5');const {plan:p}=store.create(target(100),'acct','planner');expect(p.actions).toEqual([expect.objectContaining({kind:'OPEN',quoteQuantity:'50',side:'BUY'})]);db.close()});
 it('flattens opposite exposure before opening target exposure',()=>{const{db,store}=harness();pos(db,'s','BINANCE_FUTURE_BTC_USDT','-0.5');const {plan:p}=store.create(target(100),'acct','planner');expect(p.actions.map(a=>a.kind)).toEqual(['FLATTEN','OPEN']);expect(p.actions[0]).toMatchObject({side:'BUY',reduceOnly:true,quoteQuantity:'50'});db.close()});
 it('flattens all matching positions for a zero target',()=>{const{db,store}=harness();pos(db,'g','GATE_FUTURE_BTC_USDT','1');const {plan:p}=store.create(target(0),'acct','planner');expect(p.actions).toEqual([expect.objectContaining({kind:'FLATTEN',side:'SELL',quoteQuantity:'100'})]);db.close()});
 it('splits shadow actions by the configured order notional limit',()=>{const{db,store}=harness();const {plan:p}=store.create(target(2500),'acct','planner');expect(p.actions.map(a=>[a.quoteQuantity,a.clipIndex,a.clipCount])).toEqual([['1000',1,3],['1000',2,3],['500',3,3]]);db.close()});
 it('rejects an expired target state',()=>{const{db,store}=harness();const raw=target() as ReturnType<typeof target> & {positions:Array<ReturnType<typeof target>['positions'][number] & {valid_until_ms?:number}>};raw.positions[0]!.valid_until_ms=1000;expect(()=>store.create(raw,'acct','planner',new Date(2000))).toThrow('target_state_expired');db.close()});
 it('uses explicit phases for reverse exposure and matches canonical target symbols',()=>{const{db,store}=harness();pos(db,'s','GATE_FUTURE_BTC_USDT','-0.5');const raw=target() as ReturnType<typeof target>;raw.positions[0]!.symbol='GATE_FUTURE_BTC_USDT';const {plan}=store.create(raw,'acct','planner');expect(plan.actions.map(a=>[a.kind,a.phase,a.dependsOnPhase])).toEqual([['FLATTEN',1,null],['OPEN',2,1]]);db.close()});
 it('rejects duplicate target symbols and accounts outside the single-account boundary',()=>{const{db,store}=harness();const raw=target();raw.positions.push({...raw.positions[0]!,symbol:'GATE_FUTURE_BTC_USDT'});expect(()=>store.create(raw,'acct','planner')).toThrow('duplicate_target_symbol');expect(()=>store.create(target(),'other','planner')).toThrow('target_shadow_account_mismatch');db.close()});
 it('is idempotent for the same target and position fingerprint but changes after positions change',()=>{const{db,store}=harness();const a=store.create(target(),'acct','planner');const b=store.create(target(),'acct','planner2');expect(b.reused).toBe(true);expect(b.plan.planId).toBe(a.plan.planId);pos(db,'g','GATE_FUTURE_BTC_USDT','0.5');const c=store.create(target(),'acct','planner');expect(c.plan.planId).not.toBe(a.plan.planId);expect(store.list('acct')).toHaveLength(2);expect(store.get(c.plan.planId,'acct')?.planId).toBe(c.plan.planId);expect(store.get(c.plan.planId,'other')).toBeNull();db.close()});
});
