import {mkdtempSync,rmSync} from 'node:fs';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{afterEach,describe,expect,it}from'vitest';import{openDatabase}from'./database.js';import{TargetShadowPlanStore}from'./target-shadow-plan.js';import{buildShadowAcceptanceSummary,TargetShadowComparisonStore,compareTargetShadowPlan,type TargetShadowComparison}from'./target-shadow-comparison.js';
const dirs:string[]=[];function h(){const d=mkdtempSync(join(tmpdir(),'gct-compare-'));dirs.push(d);const db=openDatabase(join(d,'db.sqlite'),resolve(process.cwd(),'../../migrations'));return{db,plans:new TargetShadowPlanStore(db,'acct'),comparisons:new TargetShadowComparisonStore(db,'acct')}}afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true})});
const sourceFingerprint=`sha256:${'a'.repeat(64)}`;const target=(qty=0)=>({meta:{contract:'gate-crossex-target-state',contract_version:1,state_fingerprint:sourceFingerprint},positions:qty?[{symbol:'BTCUSDT',target_side:'BUY',target_quote_qty:qty,route:{mode:'AUTO',allowed_exchanges:['GATE'],prefer_exchange:'GATE'}}]:[]});const audit=(signalCount=0,shadowActions?:unknown[],targetRequestHash?:string,projectedShadowActions:unknown[]|undefined=shadowActions)=>({signal_source:'/python emit_gate_crossex_state_signals.py --state-file /opt/future/binance-exchange/artifacts/reports/real_trading_state_mainline.json',signal_count:signalCount,target_request_hash:targetRequestHash,shadow_actions:shadowActions,projected_shadow_actions:projectedShadowActions,projected_clip_notional:'1000',route:{selected:[],split_plans:[]},execution:{executed:[]},loop_started_at_ms:1000});
describe('target shadow comparison',()=>{
 it('refuses to compare without a matching target fingerprint',()=>{const{db,plans}=h();const{plan}=plans.create(target(),'acct','p',new Date(1000));const c=compareTargetShadowPlan(plan,audit(),'bridge.json',1000,new Date(2000),'1000');expect(c).toMatchObject({status:'UNCOMPARABLE',confidence:'LOW'});expect(c.reasons).toContain('target_request_fingerprint_mismatch');db.close()});
 it('matches an empty plan only with a trusted matching fingerprint and explicit empty actions',()=>{const{db,plans}=h();const{plan}=plans.create(target(),'acct','p',new Date(1000));const c=compareTargetShadowPlan(plan,audit(0,[],plan.sourceStateFingerprint),'bridge.json',1000,new Date(2000),'1000');expect(c).toMatchObject({status:'MATCH',confidence:'HIGH',reasons:[]});db.close()});
 it('marks stale or wrong-source audits uncomparable',()=>{const{db,plans}=h();const{plan}=plans.create(target(),'acct','p',new Date(1000));const c=compareTargetShadowPlan(plan,{...audit(),signal_source:'old/file.json'},'bridge.json',0,new Date(4_000_000));expect(c.status).toBe('UNCOMPARABLE');expect(c.reasons).toEqual(expect.arrayContaining(['bridge_audit_source_mismatch','bridge_audit_stale']));db.close()});
 it('compares executed legacy signals with shadow opens',()=>{const{db,plans}=h();const{plan}=plans.create(target(100),'acct','p',new Date(1000));const actions=[{kind:'OPEN',symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quoteQuantity:'100'}];const c=compareTargetShadowPlan(plan,audit(1,actions,plan.sourceStateFingerprint),'bridge.json',1000,new Date(2000),'1000');expect(c).toMatchObject({status:'MATCH',confidence:'HIGH',reasons:[],missingInLegacy:[],extraInLegacy:[]});db.close()});
 it('refuses a high-confidence match when clip execution shape differs',()=>{const{db,plans}=h();const{plan}=plans.create(target(2500),'acct','p',new Date(1000));const actions=[{kind:'OPEN',symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quoteQuantity:'2500'}];const c=compareTargetShadowPlan(plan,audit(1,actions,plan.sourceStateFingerprint),'bridge.json',1000,new Date(2000),'1000');expect(c).toMatchObject({status:'UNCOMPARABLE',confidence:'LOW'});expect(c.reasons).toContain('bridge_projected_actions_not_deterministic');db.close()});
 it('rejects projected clips whose declared limit differs from the server risk policy',()=>{const{db,plans}=h();const{plan}=plans.create(target(100),'acct','p',new Date(1000));const actions=[{kind:'OPEN',symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quoteQuantity:'100'}];const c=compareTargetShadowPlan(plan,{...audit(1,actions,plan.sourceStateFingerprint),projected_clip_notional:'500'},'bridge.json',1000,new Date(2000),'1000');expect(c.status).toBe('UNCOMPARABLE');expect(c.reasons).toContain('projected_clip_policy_mismatch');db.close()});
 it('rejects projected clips that were not deterministically derived from raw legacy actions',()=>{const{db,plans}=h();const{plan}=plans.create(target(2500),'acct','p',new Date(1000));const raw=[{kind:'OPEN',symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quoteQuantity:'2400'}];const forged=[1000,1000,500].map(quoteQuantity=>({...raw[0],quoteQuantity:String(quoteQuantity)}));const c=compareTargetShadowPlan(plan,audit(1,raw,plan.sourceStateFingerprint,forged),'bridge.json',1000,new Date(2000),'1000');expect(c.status).toBe('UNCOMPARABLE');expect(c.reasons).toContain('bridge_projected_actions_not_deterministic');db.close()});
 it('matches fixed projected clips while preserving the original legacy target action',()=>{const{db,plans}=h();const{plan}=plans.create(target(2500),'acct','p',new Date(1000));const raw=[{kind:'OPEN',symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quoteQuantity:'2500'}];const projected=[1000,1000,500].map(quoteQuantity=>({...raw[0],quoteQuantity:String(quoteQuantity)}));const c=compareTargetShadowPlan(plan,audit(1,raw,plan.sourceStateFingerprint,projected),'bridge.json',1000,new Date(2000),'1000');expect(c).toMatchObject({status:'MATCH',confidence:'HIGH',legacyActions:raw,legacyProjectedActions:projected});db.close()});
 it('rejects inconsistent bridge signal and explicit action evidence',()=>{const{db,plans}=h();const{plan}=plans.create(target(),'acct','p',new Date(1000));const c=compareTargetShadowPlan(plan,audit(1,[],plan.sourceStateFingerprint),'bridge.json',1000,new Date(2000),'1000');expect(c.status).toBe('UNCOMPARABLE');expect(c.reasons).toContain('bridge_signal_action_evidence_inconsistent');db.close()});
 it('reports action differences and refuses to infer side from route-only evidence',()=>{const{db,plans}=h();const{plan}=plans.create(target(100),'acct','p',new Date(1000));const c=compareTargetShadowPlan(plan,{...audit(1,undefined,plan.sourceStateFingerprint),route:{selected:[{exchange:'GATE',symbol:'BTCUSDT',allocated_notional:100}],split_plans:[]}},'bridge.json',1000,new Date(2000),'1000');expect(c.status).toBe('UNCOMPARABLE');expect(c.reasons).toContain('bridge_shadow_actions_unavailable');db.close()});
 it('persists and reuses comparisons without creating orders',()=>{const{db,plans,comparisons}=h();const{plan}=plans.create(target(),'acct','p',new Date(1000));const a=comparisons.create(plan,audit(),'bridge.json',1000,new Date(2000));const b=comparisons.create(plan,audit(),'bridge.json',1000,new Date(3000));expect(b.reused).toBe(true);expect(b.comparison.comparisonId).toBe(a.comparison.comparisonId);expect(comparisons.list('acct')).toHaveLength(1);expect(comparisons.list('other')).toEqual([]);expect(comparisons.summary('other',new Date(3000)).windows.days7.total).toBe(0);expect(db.prepare('SELECT COUNT(*) count FROM execution_orders').get()).toEqual({count:0});db.close()});
});

describe('shadow acceptance summary',()=>{
 const item=(createdAt:string,status:TargetShadowComparison['status']='MATCH',nonEmpty=true):TargetShadowComparison=>({comparisonId:createdAt,createdAt,accountId:'acct',shadowPlanId:'plan',bridgeAuditPath:'audit',bridgeAuditFingerprint:`hash:${createdAt}`,status,confidence:status==='UNCOMPARABLE'?'LOW':'HIGH',reasons:status==='MATCH'?[]:['reason'],shadowActions:nonEmpty?[{kind:'OPEN',symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quoteQuantity:'100'}]:[],legacyActions:[],legacyProjectedActions:[],missingInLegacy:[],extraInLegacy:[]});
 it('never counts empty matches toward read-only readiness',()=>{const now=new Date('2026-08-24T00:00:00Z');const items=[item('2026-08-20T00:00:00Z','MATCH',false),item('2026-08-24T00:00:00Z','MATCH',false)];const s=buildShadowAcceptanceSummary(items,now);expect(s.readiness).toBe('NOT_READY');expect(s.gates.observationHours.passed).toBe(false);expect(s.gates.nonEmptyHighConfidenceMatches7d.actual).toBe(0)});
 it('becomes ready only after every fixed server gate passes',()=>{const now=new Date('2026-08-24T00:00:00Z');const items=Array.from({length:20},(_,i)=>item(new Date(Date.parse('2026-08-20T00:00:00Z')+i*5*60*60_000).toISOString()));const s=buildShadowAcceptanceSummary(items,now);expect(s.readiness).toBe('READY_FOR_READ_ONLY_REVIEW');expect(Object.values(s.gates).every(g=>g.passed)).toBe(true);expect(s.actions7d.byKind.OPEN).toBe(20);expect(s.actions7d.byVenue.GATE).toBe(20)});
 it('fails readiness when a recent difference exists',()=>{const now=new Date('2026-08-24T00:00:00Z');const items=Array.from({length:20},(_,i)=>item(new Date(Date.parse('2026-08-20T00:00:00Z')+i*5*60*60_000).toISOString()));items.push(item('2026-08-23T23:00:00Z','DIFFERENT'));const s=buildShadowAcceptanceSummary(items,now);expect(s.readiness).toBe('NOT_READY');expect(s.gates.different24h).toMatchObject({actual:1,passed:false})});
 it('excludes invalid future and duplicate audit evidence',()=>{const now=new Date('2026-08-24T00:00:00Z');const valid=item('2026-08-23T00:00:00Z');const duplicate={...item('2026-08-23T01:00:00Z'),bridgeAuditFingerprint:valid.bridgeAuditFingerprint};const s=buildShadowAcceptanceSummary([valid,duplicate,item('invalid'),item('2026-08-25T00:00:00Z')],now);expect(s.windows.days7.total).toBe(1);expect(s.gates.nonEmptyHighConfidenceMatches7d.actual).toBe(1)});
 it('does not let uncomparable samples extend readiness observation hours',()=>{const now=new Date('2026-08-24T00:00:00Z');const items=[item('2026-08-18T00:00:00Z','UNCOMPARABLE'),item('2026-08-23T20:00:00Z'),item('2026-08-23T22:00:00Z'),item('2026-08-24T00:00:00Z','UNCOMPARABLE')];const s=buildShadowAcceptanceSummary(items,now);expect(s.gates.observationHours.actual).toBe(2);expect(s.actions7d.byKind.OPEN).toBe(2)});
 it('treats an empty target as a break in the non-empty match streak',()=>{const now=new Date('2026-08-24T00:00:00Z');const items=[item('2026-08-23T20:00:00Z'),item('2026-08-23T21:00:00Z','MATCH',false),item('2026-08-23T22:00:00Z')];const s=buildShadowAcceptanceSummary(items,now);expect(s.gates.consecutiveNonEmptyHighConfidenceMatches.actual).toBe(1)});
});
