import {mkdtempSync,rmSync} from 'node:fs';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{afterEach,describe,expect,it}from'vitest';import{openDatabase}from'./database.js';import{TargetShadowPlanStore}from'./target-shadow-plan.js';import{TargetShadowComparisonStore,compareTargetShadowPlan}from'./target-shadow-comparison.js';
const dirs:string[]=[];function h(){const d=mkdtempSync(join(tmpdir(),'gct-compare-'));dirs.push(d);const db=openDatabase(join(d,'db.sqlite'),resolve(process.cwd(),'../../migrations'));return{db,plans:new TargetShadowPlanStore(db,'acct'),comparisons:new TargetShadowComparisonStore(db,'acct')}}afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true})});
const sourceFingerprint=`sha256:${'a'.repeat(64)}`;const target=(qty=0)=>({meta:{contract:'gate-crossex-target-state',contract_version:1,state_fingerprint:sourceFingerprint},positions:qty?[{symbol:'BTCUSDT',target_side:'BUY',target_quote_qty:qty,route:{mode:'AUTO',allowed_exchanges:['GATE'],prefer_exchange:'GATE'}}]:[]});const audit=(signalCount=0,shadowActions?:unknown[],targetRequestHash?:string)=>({signal_source:'/python emit_gate_crossex_state_signals.py --state-file /opt/future/binance-exchange/artifacts/reports/real_trading_state_mainline.json',signal_count:signalCount,target_request_hash:targetRequestHash,shadow_actions:shadowActions,route:{selected:[],split_plans:[]},execution:{executed:[]},loop_started_at_ms:1000});
describe('target shadow comparison',()=>{
 it('refuses to compare without a matching target fingerprint',()=>{const{db,plans}=h();const{plan}=plans.create(target(),'acct','p',new Date(1000));const c=compareTargetShadowPlan(plan,audit(),'bridge.json',1000,new Date(2000));expect(c).toMatchObject({status:'UNCOMPARABLE',confidence:'LOW'});expect(c.reasons).toContain('target_request_fingerprint_mismatch');db.close()});
 it('matches an empty plan only with a trusted matching fingerprint and explicit empty actions',()=>{const{db,plans}=h();const{plan}=plans.create(target(),'acct','p',new Date(1000));const c=compareTargetShadowPlan(plan,audit(0,[],plan.sourceStateFingerprint),'bridge.json',1000,new Date(2000));expect(c).toMatchObject({status:'MATCH',confidence:'HIGH',reasons:[]});db.close()});
 it('marks stale or wrong-source audits uncomparable',()=>{const{db,plans}=h();const{plan}=plans.create(target(),'acct','p',new Date(1000));const c=compareTargetShadowPlan(plan,{...audit(),signal_source:'old/file.json'},'bridge.json',0,new Date(4_000_000));expect(c.status).toBe('UNCOMPARABLE');expect(c.reasons).toEqual(expect.arrayContaining(['bridge_audit_source_mismatch','bridge_audit_stale']));db.close()});
 it('compares executed legacy signals with shadow opens',()=>{const{db,plans}=h();const{plan}=plans.create(target(100),'acct','p',new Date(1000));const actions=[{kind:'OPEN',symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quoteQuantity:'100'}];const c=compareTargetShadowPlan(plan,audit(1,actions,plan.sourceStateFingerprint),'bridge.json',1000,new Date(2000));expect(c).toMatchObject({status:'MATCH',confidence:'HIGH',reasons:[],missingInLegacy:[],extraInLegacy:[]});db.close()});
 it('compares repeated clips as an aggregated action multiset',()=>{const{db,plans}=h();const{plan}=plans.create(target(2500),'acct','p',new Date(1000));const actions=[1000,1000,500].map(quoteQuantity=>({kind:'OPEN',symbol:'GATE_FUTURE_BTC_USDT',venue:'GATE',side:'BUY',quoteQuantity:String(quoteQuantity)}));const c=compareTargetShadowPlan(plan,audit(3,actions,plan.sourceStateFingerprint),'bridge.json',1000,new Date(2000));expect(c.status).toBe('MATCH');db.close()});
 it('reports action differences and refuses to infer side from route-only evidence',()=>{const{db,plans}=h();const{plan}=plans.create(target(100),'acct','p',new Date(1000));const c=compareTargetShadowPlan(plan,{...audit(1,undefined,plan.sourceStateFingerprint),route:{selected:[{exchange:'GATE',symbol:'BTCUSDT',allocated_notional:100}],split_plans:[]}},'bridge.json',1000,new Date(2000));expect(c.status).toBe('UNCOMPARABLE');expect(c.reasons).toContain('bridge_shadow_actions_unavailable');db.close()});
 it('persists and reuses comparisons without creating orders',()=>{const{db,plans,comparisons}=h();const{plan}=plans.create(target(),'acct','p',new Date(1000));const a=comparisons.create(plan,audit(),'bridge.json',1000,new Date(2000));const b=comparisons.create(plan,audit(),'bridge.json',1000,new Date(3000));expect(b.reused).toBe(true);expect(b.comparison.comparisonId).toBe(a.comparison.comparisonId);expect(comparisons.list()).toHaveLength(1);expect(db.prepare('SELECT COUNT(*) count FROM execution_orders').get()).toEqual({count:0});db.close()});
});
