import { createHash, randomUUID } from 'node:crypto';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import type Database from 'better-sqlite3';
import { Decimal } from 'decimal.js';
import { z } from 'zod';
import type { ShadowAction, TargetShadowPlan } from './target-shadow-plan.js';
const ComparableActionSchema=z.object({kind:z.enum(['FLATTEN','REDUCE','OPEN']),symbol:z.string(),venue:z.string(),side:z.enum(['BUY','SELL']),quoteQuantity:z.string().regex(/^\d+(?:\.\d+)?$/)});
const AuditSchema=z.object({signal_source:z.string().default(''),signal_count:z.number().int().nonnegative().default(0),target_request_hash:z.string().optional(),shadow_actions:z.array(ComparableActionSchema).optional(),projected_shadow_actions:z.array(ComparableActionSchema).optional(),projected_clip_notional:z.string().regex(/^\d+(?:\.\d+)?$/).optional(),loop_started_at_ms:z.number().int().nonnegative().optional(),route:z.object({selected:z.array(z.record(z.string(),z.unknown())).default([]),split_plans:z.array(z.record(z.string(),z.unknown())).default([])}).passthrough().default({selected:[],split_plans:[]}),execution:z.object({executed:z.array(z.record(z.string(),z.unknown())).default([])}).passthrough().default({executed:[]})}).passthrough();
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(',')}}`;return JSON.stringify(v)}
function hash(v:unknown){return`sha256:${createHash('sha256').update(canonical(v)).digest('hex')}`}
export interface ComparableAction{kind:'FLATTEN'|'REDUCE'|'OPEN';symbol:string;venue:string;side:'BUY'|'SELL';quoteQuantity:string}
function shadowActions(plan:TargetShadowPlan):ComparableAction[]{return plan.actions.map(a=>({kind:a.kind,symbol:a.symbol,venue:a.venue,side:a.side,quoteQuantity:a.quoteQuantity}))}
function normalizeActions(actions:z.infer<typeof ComparableActionSchema>[]):ComparableAction[]{return actions.map(action=>({...action,symbol:action.symbol.toUpperCase(),venue:action.venue.toUpperCase(),quoteQuantity:new Decimal(action.quoteQuantity).toFixed()}))}
function legacyActions(raw:z.infer<typeof AuditSchema>):ComparableAction[]{return normalizeActions(raw.shadow_actions??[])}
function projectedLegacyActions(raw:z.infer<typeof AuditSchema>):ComparableAction[]{return normalizeActions(raw.projected_shadow_actions??[])}
function aggregate(actions:ComparableAction[]):Map<string,Decimal>{const out=new Map<string,Decimal>();for(const a of actions){const key=`${a.kind}|${a.symbol}|${a.venue}|${a.side}`;out.set(key,(out.get(key)??new Decimal(0)).add(a.quoteQuantity))}return out}
function orderedActionShape(actions:ComparableAction[]){return actions.map(a=>`${a.kind}|${a.symbol}|${a.venue}|${a.side}|${new Decimal(a.quoteQuantity).toFixed()}`)}
function actionShape(actions:ComparableAction[]){return orderedActionShape(actions).sort()}
function compactKinds(actions:ComparableAction[]){return actions.map(a=>a.kind).filter((kind,index,all)=>index===0||kind!==all[index-1])}
function projectActions(actions:ComparableAction[],limitValue:string):ComparableAction[]{const limit=new Decimal(limitValue);return actions.flatMap(action=>{let remaining=new Decimal(action.quoteQuantity);const count=remaining.div(limit).ceil().toNumber();return Array.from({length:count},()=>{const amount=Decimal.min(remaining,limit);remaining=remaining.sub(amount);return{...action,quoteQuantity:amount.toFixed()}})})}
export interface TargetShadowComparison{comparisonId:string;createdAt:string;accountId:string;shadowPlanId:string;bridgeAuditPath:string;bridgeAuditFingerprint:string;status:'MATCH'|'DIFFERENT'|'UNCOMPARABLE';confidence:'LOW'|'HIGH';reasons:string[];shadowActions:ComparableAction[];legacyActions:ComparableAction[];legacyProjectedActions:ComparableAction[];missingInLegacy:ComparableAction[];extraInLegacy:ComparableAction[]}
export interface ShadowAcceptanceSummary{generatedAt:string;readiness:'READY_FOR_READ_ONLY_REVIEW'|'NOT_READY';gates:{observationHours:{actual:number;required:number;passed:boolean};nonEmptyHighConfidenceMatches7d:{actual:number;required:number;passed:boolean};consecutiveNonEmptyHighConfidenceMatches:{actual:number;required:number;passed:boolean};different24h:{actual:number;required:number;passed:boolean};uncomparable24h:{actual:number;required:number;passed:boolean}};windows:{hours24:Record<TargetShadowComparison['status'],number>&{total:number;empty:number;nonEmpty:number};days7:Record<TargetShadowComparison['status'],number>&{total:number;empty:number;nonEmpty:number}};actions7d:{byKind:Record<ComparableAction['kind'],number>;byVenue:Record<string,number>};recentReasons:Record<string,number>;sampleRange:{firstAt:string|null;lastAt:string|null}}
function windowStats(items:TargetShadowComparison[]){return items.reduce((out,item)=>{out.total+=1;out[item.status]+=1;(item.shadowActions.length===0?out.empty++:out.nonEmpty++);return out},{total:0,MATCH:0,DIFFERENT:0,UNCOMPARABLE:0,empty:0,nonEmpty:0})}
export function buildShadowAcceptanceSummary(items:TargetShadowComparison[],now=new Date()):ShadowAcceptanceSummary{const nowMs=now.getTime(),since24=nowMs-24*60*60_000,since7d=nowMs-7*24*60*60_000,seen=new Set<string>();const sorted=[...items].filter(item=>{const at=Date.parse(item.createdAt);if(!Number.isFinite(at)||at<since7d||at>nowMs||seen.has(item.bridgeAuditFingerprint))return false;seen.add(item.bridgeAuditFingerprint);return true}).sort((a,b)=>Date.parse(a.createdAt)-Date.parse(b.createdAt)),items24=sorted.filter(item=>Date.parse(item.createdAt)>=since24),items7=sorted;const nonEmpty7=items7.filter(item=>item.shadowActions.length>0),matches7=nonEmpty7.filter(item=>item.status==='MATCH'&&item.confidence==='HIGH').length;let consecutive=0;for(const item of [...items7].reverse()){if(item.shadowActions.length>0&&item.status==='MATCH'&&item.confidence==='HIGH')consecutive+=1;else break}const comparable7=items7.filter(item=>item.shadowActions.length>0&&item.status!=='UNCOMPARABLE'&&item.confidence==='HIGH'),first=comparable7[0]?.createdAt??null,last=comparable7.at(-1)?.createdAt??null,observationHours=first&&last?Math.max(0,(Date.parse(last)-Date.parse(first))/3_600_000):0;const byKind={FLATTEN:0,REDUCE:0,OPEN:0},byVenue:Record<string,number>={};for(const item of comparable7)for(const action of item.shadowActions){byKind[action.kind]+=1;byVenue[action.venue]=(byVenue[action.venue]??0)+1}const reasons:Record<string,number>={};for(const item of items7)for(const reason of item.reasons)reasons[reason]=(reasons[reason]??0)+1;const gates={observationHours:{actual:Number(observationHours.toFixed(2)),required:72,passed:observationHours>=72},nonEmptyHighConfidenceMatches7d:{actual:matches7,required:20,passed:matches7>=20},consecutiveNonEmptyHighConfidenceMatches:{actual:consecutive,required:10,passed:consecutive>=10},different24h:{actual:items24.filter(item=>item.status==='DIFFERENT').length,required:0,passed:items24.every(item=>item.status!=='DIFFERENT')},uncomparable24h:{actual:items24.filter(item=>item.status==='UNCOMPARABLE').length,required:0,passed:items24.every(item=>item.status!=='UNCOMPARABLE')}};return{generatedAt:now.toISOString(),readiness:Object.values(gates).every(gate=>gate.passed)?'READY_FOR_READ_ONLY_REVIEW':'NOT_READY',gates,windows:{hours24:windowStats(items24),days7:windowStats(items7)},actions7d:{byKind,byVenue},recentReasons:reasons,sampleRange:{firstAt:first,lastAt:last}}}
export function compareTargetShadowPlan(plan:TargetShadowPlan,auditRaw:unknown,path:string,auditMtimeMs:number,now=new Date(),expectedClipNotional?:string):TargetShadowComparison{
  const audit=AuditSchema.parse(auditRaw),shadow=shadowActions(plan),legacy=legacyActions(audit),projected=projectedLegacyActions(audit),serverProjected=expectedClipNotional?projectActions(legacy,expectedClipNotional):[],reasons:string[]=[];
  const ageMs=now.getTime()-auditMtimeMs;
  if(!audit.signal_source.includes('real_trading_state_mainline.json'))reasons.push('bridge_audit_source_mismatch');
  if(ageMs<0||ageMs>30*60_000)reasons.push('bridge_audit_stale');
  if(!plan.sourceStateFingerprint||audit.target_request_hash!==plan.sourceStateFingerprint)reasons.push('target_request_fingerprint_mismatch');
  if(audit.shadow_actions===undefined)reasons.push('bridge_shadow_actions_unavailable');
  if(audit.projected_shadow_actions===undefined)reasons.push('bridge_projected_actions_unavailable');
  if(!expectedClipNotional||!audit.projected_clip_notional||!new Decimal(audit.projected_clip_notional).eq(expectedClipNotional))reasons.push('projected_clip_policy_mismatch');
  if((audit.signal_count===0&&legacy.length>0)||(audit.signal_count>0&&legacy.length===0))reasons.push('bridge_signal_action_evidence_inconsistent');
  if((legacy.length===0&&projected.length>0)||(legacy.length>0&&projected.length===0))reasons.push('bridge_projected_action_evidence_inconsistent');
  if(JSON.stringify(orderedActionShape(projected))!==JSON.stringify(orderedActionShape(serverProjected)))reasons.push('bridge_projected_actions_not_deterministic');
  const sa=aggregate(shadow),la=aggregate(serverProjected),differentKeys=new Set<string>();
  for(const key of new Set([...sa.keys(),...la.keys()]))if(!(sa.get(key)??new Decimal(0)).eq(la.get(key)??new Decimal(0)))differentKeys.add(key);
  const actionKey=(a:ComparableAction)=>`${a.kind}|${a.symbol}|${a.venue}|${a.side}`;
  const missing=shadow.filter(a=>differentKeys.has(actionKey(a))),extra=legacy.filter(a=>differentKeys.has(actionKey(a)));
  let status:TargetShadowComparison['status'],confidence:TargetShadowComparison['confidence'];
  const shapeMatches=JSON.stringify(actionShape(shadow))===JSON.stringify(actionShape(serverProjected));
  const orderingMatches=JSON.stringify(compactKinds(shadow))===JSON.stringify(compactKinds(serverProjected));
  if(reasons.length>0){status='UNCOMPARABLE';confidence='LOW'}else if(differentKeys.size>0){status='DIFFERENT';confidence='HIGH';reasons.push('aggregated_actions_differ')}else if(!shapeMatches||!orderingMatches){status='UNCOMPARABLE';confidence='LOW';if(!shapeMatches)reasons.push('execution_shape_differs');if(!orderingMatches)reasons.push('action_ordering_differs')}else{status='MATCH';confidence='HIGH'}
  return{comparisonId:randomUUID(),createdAt:now.toISOString(),accountId:plan.accountId,shadowPlanId:plan.planId,bridgeAuditPath:path,bridgeAuditFingerprint:hash(auditRaw),status,confidence,reasons,shadowActions:shadow,legacyActions:legacy,legacyProjectedActions:projected,missingInLegacy:missing,extraInLegacy:extra}
}
export function readLatestBridgeAudit(directory:string):{audit:unknown;path:string;mtimeMs:number}{const names=readdirSync(directory).filter(name=>/^bridge_run_\d+_\d{8}_\d{6}\.json$/.test(name));if(names.length===0)throw new Error('bridge_audit_unavailable');const rows=names.map(name=>{const path=join(directory,name),stat=statSync(path);return{path,mtimeMs:stat.mtimeMs}}).sort((a,b)=>b.mtimeMs-a.mtimeMs);const latest=rows[0]!;return{...latest,audit:JSON.parse(readFileSync(latest.path,'utf8'))}}
export class TargetShadowComparisonStore{
  constructor(private readonly db:Database.Database,private readonly accountId:string){}
  create(plan:TargetShadowPlan,audit:unknown,path:string,mtime:number,now=new Date()):{comparison:TargetShadowComparison;reused:boolean}{
    if(plan.accountId!==this.accountId)throw new Error('target_shadow_comparison_account_mismatch');const policy=this.db.prepare('SELECT max_order_notional FROM execution_risk_guard WHERE id=1').get() as {max_order_notional:string};const c=compareTargetShadowPlan(plan,audit,path,mtime,now,policy.max_order_notional);
    return this.db.transaction(()=>{const result=this.db.prepare(`INSERT INTO target_shadow_comparisons(id,account_id,shadow_plan_id,bridge_audit_path,bridge_audit_fingerprint,status,confidence,comparison_json,created_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,shadow_plan_id,bridge_audit_fingerprint) DO NOTHING`).run(c.comparisonId,c.accountId,c.shadowPlanId,c.bridgeAuditPath,c.bridgeAuditFingerprint,c.status,c.confidence,JSON.stringify(c),c.createdAt);if(result.changes===1)return{comparison:c,reused:false};const old=this.db.prepare('SELECT comparison_json FROM target_shadow_comparisons WHERE account_id=? AND shadow_plan_id=? AND bridge_audit_fingerprint=?').get(this.accountId,plan.planId,c.bridgeAuditFingerprint) as {comparison_json:string};return{comparison:JSON.parse(old.comparison_json) as TargetShadowComparison,reused:true}})()
  }
  list(accountId:string){if(accountId!==this.accountId)return[];return(this.db.prepare('SELECT comparison_json FROM target_shadow_comparisons WHERE account_id=? ORDER BY created_at DESC LIMIT 50').all(accountId)as Array<{comparison_json:string}>).map(r=>JSON.parse(r.comparison_json) as TargetShadowComparison)}
  summary(accountId:string,now=new Date()){if(accountId!==this.accountId)return buildShadowAcceptanceSummary([],now);const since=new Date(now.getTime()-7*24*60*60_000).toISOString();const items=(this.db.prepare('SELECT comparison_json FROM target_shadow_comparisons WHERE account_id=? AND created_at>=? AND created_at<=? ORDER BY created_at ASC').all(accountId,since,now.toISOString())as Array<{comparison_json:string}>).map(r=>JSON.parse(r.comparison_json) as TargetShadowComparison);return buildShadowAcceptanceSummary(items,now)}
}
